// Code generated by mockery v2.26.1. DO NOT EDIT.

package cusservice

import mock "github.com/stretchr/testify/mock"

// mockServiceUtils is an autogenerated mock type for the serviceUtils type
type mockServiceUtils struct {
	mock.Mock
}

// createCustomers provides a mock function with given fields:
func (_m *mockServiceUtils) createCustomers() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTnewMockServiceUtils interface {
	mock.TestingT
	Cleanup(func())
}

// newMockServiceUtils creates a new instance of mockServiceUtils. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newMockServiceUtils(t mockConstructorTestingTnewMockServiceUtils) *mockServiceUtils {
	mock := &mockServiceUtils{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
