// Code generated by mockery v2.33.3. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "labForBosz/internal/core/domain"
	fn "labForBosz/internal/core/domain/fn"

	mock "github.com/stretchr/testify/mock"
)

// CustomerService is an autogenerated mock type for the CustomerService type
type CustomerService struct {
	mock.Mock
}

// CreateCustomer provides a mock function with given fields: ctx, in
func (_m *CustomerService) CreateCustomer(ctx context.Context, in domain.Customer) (*int, error) {
	ret := _m.Called(ctx, in)

	var r0 *int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Customer) (*int, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Customer) *int); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*int)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Customer) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateCustomerAddress provides a mock function with given fields: ctx, in
func (_m *CustomerService) CreateCustomerAddress(ctx context.Context, in domain.CreateCustomerAddress) (*int, error) {
	ret := _m.Called(ctx, in)

	var r0 *int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.CreateCustomerAddress) (*int, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.CreateCustomerAddress) *int); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*int)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.CreateCustomerAddress) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateCustomerAddressTransactional provides a mock function with given fields: ctx, in, f
func (_m *CustomerService) CreateCustomerAddressTransactional(ctx context.Context, in domain.CreateCustomerAddress, f fn.CreateCustomerAddressFn) (*int, error) {
	ret := _m.Called(ctx, in, f)

	var r0 *int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.CreateCustomerAddress, fn.CreateCustomerAddressFn) (*int, error)); ok {
		return rf(ctx, in, f)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.CreateCustomerAddress, fn.CreateCustomerAddressFn) *int); ok {
		r0 = rf(ctx, in, f)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*int)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.CreateCustomerAddress, fn.CreateCustomerAddressFn) error); ok {
		r1 = rf(ctx, in, f)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCustomer provides a mock function with given fields: ctx
func (_m *CustomerService) GetCustomer(ctx context.Context) ([]domain.Customer, error) {
	ret := _m.Called(ctx)

	var r0 []domain.Customer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.Customer, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.Customer); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Customer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCustomerbyId provides a mock function with given fields: ctx, id
func (_m *CustomerService) GetCustomerbyId(ctx context.Context, id int) (*domain.Customer, error) {
	ret := _m.Called(ctx, id)

	var r0 *domain.Customer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*domain.Customer, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *domain.Customer); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Customer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateCustomer provides a mock function with given fields: ctx, in
func (_m *CustomerService) UpdateCustomer(ctx context.Context, in domain.Customer) error {
	ret := _m.Called(ctx, in)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Customer) error); ok {
		r0 = rf(ctx, in)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCustomerService creates a new instance of CustomerService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCustomerService(t interface {
	mock.TestingT
	Cleanup(func())
}) *CustomerService {
	mock := &CustomerService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
